/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajopatronessoftware;

import factoryMethod.FactoriasVenta;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import pieza.*;

/**
 *
 * @author nano
 */
public class CarritoCompra extends javax.swing.JFrame {

    /**
     * Creates new form CarritoCompra
     */
    
    private Cliente cliente;
    private DefaultTableModel modeloTabla;
    private int posicionElegidaTabla;
    private ArrayList<Pieza> piezasCarrito;
    private FactoriasVenta factoriaVentas ;
    private DatosPrograma datos;
    
    public CarritoCompra() {
       initComponents();
    }
    public CarritoCompra(Cliente c, DatosPrograma d) {
       initComponents();
        
        setTitle("Carrito de compra");
        datos=d;
        cliente=c;     
        factoriaVentas = new FactoriasVenta(cliente);
        modeloTabla =  (DefaultTableModel) jTable1.getModel();
        setTitle("Lista de compras realizadas en el desguace");
        rellenarTabla();
        
    }
    //Rellena la tabla con las compras realizadas por el usuario
    public void rellenarTabla(){
       piezasCarrito=cliente.getCarritoCompra();
        
       while (modeloTabla.getRowCount()>0)         
        {
            modeloTabla.removeRow(0);
        } 
       
      // ArrayList <Pieza> piezasCarrito = cliente.getCarritoCompra();
       
       for (int i=0 ; i< piezasCarrito.size();i++){
       
            modeloTabla.addRow(new Object[]{piezasCarrito.get(i).getNombre(),
                            piezasCarrito.get(i).getMarca(),
                            piezasCarrito.get(i).getModelo(),
                            String.valueOf(piezasCarrito.get(i).getAño()),
                            piezasCarrito.get(i).getEstado(),
                            Float.toString(piezasCarrito.get(i).getPrecio())});
                    }
       DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            jTable1.getColumnModel().getColumn(0).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(1).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(2).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(3).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(4).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(5).setCellRenderer(tcr);
    }
    //MUESTRA EN EL JFRAME EL NUMERO DE PIEZAS QUE HAN SIDO SELECCIONADAS Y CUAL ES EL PRECIO A PAAGR POR ELLAS
    public void piezasSeleccionadas(){
        int posicionPiezas [] = jTable1.getSelectedRows();
        if (posicionPiezas.length>0){
            jTextFieldNumeroPiezas.setText(posicionPiezas.length+"");
            float precioPiezas=0f;
            for (int i=0;i<posicionPiezas.length;i++){
                precioPiezas += piezasCarrito.get(posicionPiezas[i]).getPrecio();
            }
            jTextFieldPrecioPiezas.setText(""+precioPiezas);
        }
        else{
            jTextFieldNumeroPiezas.setText("0");
            jTextFieldPrecioPiezas.setText("0.0");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonComprarDelCarrito = new javax.swing.JButton();
        jButtonEliminarDelCarrito = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNumeroPiezas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrecioPiezas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pieza", "Marca", "Modelo", "Año", "Estado", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jButtonComprarDelCarrito.setText("Comprar");
        jButtonComprarDelCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarDelCarritoActionPerformed(evt);
            }
        });

        jButtonEliminarDelCarrito.setText("Eliminar del carrito");
        jButtonEliminarDelCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarDelCarritoActionPerformed(evt);
            }
        });

        jLabel1.setText("Tras seleccionar todos los objetos del carrito que desee comprar u eliminar");

        jLabel2.setText(" pulse un boton (puede seleccionar varias entradas utilizando SHIFT + click");

        jLabel3.setText("Piezas seleccionadas: ");

        jTextFieldNumeroPiezas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNumeroPiezas.setText("0");
        jTextFieldNumeroPiezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroPiezasActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio estimado a pagar: ");

        jTextFieldPrecioPiezas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecioPiezas.setText("0.0");
        jTextFieldPrecioPiezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioPiezasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumeroPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPrecioPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextFieldPrecioPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldNumeroPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonComprarDelCarrito)
                                .addGap(23, 23, 23))
                            .addComponent(jButtonEliminarDelCarrito, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonComprarDelCarrito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminarDelCarrito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
       piezasSeleccionadas();
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        piezasSeleccionadas();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextFieldNumeroPiezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroPiezasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroPiezasActionPerformed

    private void jTextFieldPrecioPiezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioPiezasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioPiezasActionPerformed

    private void jButtonComprarDelCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarDelCarritoActionPerformed
        // TODO add your handling code here:
        ArrayList<Pieza> arrayAuxiliar = new ArrayList<Pieza>();
        int piezasCarritoAñadir[]=jTable1.getSelectedRows();
        
        //Si el usuario ha seleccionado alguna pieza del carrito para comprar 
        if (piezasCarritoAñadir.length<=0){
            JOptionPane.showMessageDialog(this, "Asegurate de que has escogido al menos un articulo para comprar","Error realizar compra",JOptionPane.WARNING_MESSAGE);  
        }
        //Si el usuario ha seleccionado alguna pieza del carrito para comprar
        else{
            for (int i=0;i<piezasCarritoAñadir.length;i++){
                //Añade al array auxiliar las piezas seleccionadas del carrito
                arrayAuxiliar.add(piezasCarrito.get(piezasCarritoAñadir[i]));
            }
            int respuesta = JOptionPane.showConfirmDialog(this, "Si quiere la compra genere un ticket pulse SI y CANCELAR para cancelar la operacion", "Compra", JOptionPane.YES_NO_CANCEL_OPTION);
            if (respuesta == 1 ){   //SI
                //Se añade la venta al usuario
                cliente.añadirVenta(factoriaVentas.getVenta(true, arrayAuxiliar));
                //Se eliminan las piezas del sistema
                for (int i=0; i<arrayAuxiliar.size();i++){
                    datos.eliminarPieza(arrayAuxiliar.get(i));
                    cliente.eliminarPiezaCarrito(arrayAuxiliar.get(i));
                }
            }
            else if(respuesta == 0){  //NO 
                //Se añade la venta al usuario
                cliente.añadirVenta(factoriaVentas.getVenta(false, arrayAuxiliar));
                //Se eliminan las piezas del sistema
                for (int i=0; i<arrayAuxiliar.size();i++){
                    datos.eliminarPieza(arrayAuxiliar.get(i));
                    cliente.eliminarPiezaCarrito(arrayAuxiliar.get(i));
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Compra cancelada","Compra",JOptionPane.WARNING_MESSAGE);  
            }
            rellenarTabla();
        }
        
    }//GEN-LAST:event_jButtonComprarDelCarritoActionPerformed

    private void jButtonEliminarDelCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarDelCarritoActionPerformed
        // TODO add your handling code here:
        int posicionesParaEliminar[]=jTable1.getSelectedRows();
        if (posicionesParaEliminar.length<1){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione uno o varios elementos para que puedan ser eliminados del carrito","Error de borrado",JOptionPane.WARNING_MESSAGE);  
        }
        else{
            for (int i=0; i < posicionesParaEliminar.length; i++){
            cliente.eliminarPiezaCarrito(piezasCarrito.get(posicionesParaEliminar[i]));
            }
            if (posicionesParaEliminar.length>1)
            JOptionPane.showMessageDialog(this, "Las piezas han sido borradas con éxito","Borrado de piezas",JOptionPane.INFORMATION_MESSAGE);  
            else
            JOptionPane.showMessageDialog(this, "La pieza ha sido borrada con éxito","Borrado de piezas",JOptionPane.INFORMATION_MESSAGE);    
            rellenarTabla();
        }
    }//GEN-LAST:event_jButtonEliminarDelCarritoActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        piezasSeleccionadas();
    }//GEN-LAST:event_jTable1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarritoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarritoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarritoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarritoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarritoCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonComprarDelCarrito;
    private javax.swing.JButton jButtonEliminarDelCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldNumeroPiezas;
    private javax.swing.JTextField jTextFieldPrecioPiezas;
    // End of variables declaration//GEN-END:variables
}
